### ISSUE TITLE
AttitubeError in _Sequence_HDF5 __del__ method

### ISSUE THREAD

**Issue by nbdanielson** [losonczylab/sima#100]
When the __del__ method is called, an AttibuteError is raised:

![junk](https://cloud.githubusercontent.com/assets/8344546/5843829/56922984-a17d-11e4-8777-cf08be44c53c.png)

**Comment by pkaifosh** [comment]
This bug should not actually be stopping your code from running, since Exceptions in ```__del__```() methods are just printed to stdout and otherwise have no effect.

I can't reproduce the error with just creating and deleting a Sequence object. Can you give more information on what code was being run here?

**Comment by jzaremba** [comment]
@nbdanielson Do you have an example that generates this error or can we close this?
