### ISSUE TITLE
Fast loading of datasets

### ISSUE THREAD

**Issue by jzaremba** [losonczylab/sima#104]
It should be possible to load any SIMA dataset nearly instantaneously, without requiring to read any raw data.

Currently Sequence data is stored within dataset.pkl, which can get relatively large (~50-100MB after motion correcting data). It's not really an issue for data stored locally, but for loading SIMA datasets stored remotely, the entire file needs to be transferred over the network, which can be prohibitively slow.

Desired use: Install ROI_Buddy locally, load remote datasets over samba/CIFS.

Suggested solution: Pull all sequence data out of dataset.pkl in to a sequences.pkl (?) file. If you don't try to iterate over a dataset you shouldn't need access to any of the raw data, motion correction displacements, etc.

**Comment by pkaifosh** [comment]
I like the suggested change. Do you want one file per sequence, or just one sequences.pkl file? If we don't see any advantageous to splitting, I guess one sequences.pkl file is simplest. Let's make this change before releasing 1.0

**Comment by jzaremba** [comment]
I think one sequences.pkl is the simplest, and right now I don't think I see a reason to split them up. I'll probably move a few ImagingDataset attributes to properties that can be lazy loaded (sequences, frame_shape, num_frames).

We could also potentially calculate the frame_shape from the time_averages.pkl instead of the sequences directly? Might leave that out for now, but I'll at least make sure the __repr__ doesn't trigger the loading/calculating of any of those properties.

**Comment by jzaremba** [comment]
How should we handle old datasets from before this change? It would be nice to keep the ImagingDataset init clean, so let it fail and add cases to convert.py like we do with 0.x sets now?

**Comment by pkaifosh** [comment]
We could do that, or just run a script to convert all of our existing 1.0.0-dev datasets.

**Comment by jzaremba** [comment]
This is mostly implemented now. Still testing and working on a convert script for our dev sets, but In short:

- ImagingDataset.sequences is not stored in a separate sequences.pkl file within the sima directory instead of within dataset.pkl
-ImagingDataset.sequences, num_frames, frame_shape, and num_sequences have all be changed from attributes to properties that are lazy-loaded as needed.
-frame_shape and num_sequences are also stored in dataset.pkl so they don't need to be re'calc'd every re-load.

dataset.pkl will be much smaller now and doesn't actually need any of the sequence data until you actually start iterating over it (Note: Calling ImagingDataset.save() will load everything to then save it all).
This will also make it easier to move/share datasets, as you will still be able to load ImagingDatasets, look at time_averages, manage ROIs, etc., without having any of the raw data.

**Comment by jzaremba** [comment]
Resolved by #105.
