### ISSUE TITLE
sima import failure in 1.0.x

### ISSUE THREAD

**Issue by nk53** [losonczylab/sima#119]
`import sima` results in:
>Traceback (most recent call last):
>  File "./stica_test.py", line 3, in \<module\>
>    import sima
>  File "/Library/Python/2.7/site-packages/sima/\__init\__.py", line 6, in \<module\>
>    from sima.imaging import ImagingDataset
>  File "/Library/Python/2.7/site-packages/sima/imaging.py", line 5, in \<module\>
>    from future import standard_library
>ImportError: No module named future

**Comment by pkaifosh** [comment]
Hi. You just need to install future with pip:

```
>>> pip install future
```

I assume you are running of the master branch? Anyway, future is now listed among the dependencies.

**Comment by nk53** [comment]
I'll do that, however I was actually on the 1.0.x branch
