### ISSUE TITLE
csv.writer() doesn't accept unicode literals

### ISSUE THREAD

**Issue by nk53** [losonczylab/sima#122]
the line `writer = csv.writer(csvfile, delimieter='\t')` in sima/imaging.py (line 620) fails with `TypeError: "delimiter" must be string, not unicode`.

Here's the full error message:
>Traceback (most recent call last):
>  File "./signal.py", line 17, in \<module\>
>    dataset.export_signals('all.csv')
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sima/imaging.py", line 620, in export_signals
>    writer = csv.writer(csvfile, delimiter='\t')
.TypeError: "delimiter" must be string, not unicode

**Comment by pkaifosh** [comment]
Thanks for the report. Can you send the code required to trigger this error?

**Comment by nk53** [comment]
This should contain the relevant files. `signal.py` is the one producing the error.
https://drive.google.com/file/d/0B5tB6Q_10OpTWVVGUWJSa3hPZWc/view?usp=sharing

**Comment by pkaifosh** [comment]
OK, thanks. I've found the problem (specific to the master branch) and will fix it asap.
