### ISSUE TITLE
Crash while loading tiff file

### ISSUE THREAD

**Issue by celialoriette** [losonczylab/sima#130]
Hi,
I managed to make sima working but I just can't load my tif files. Python crashes systematically while I am doing this step :

dataset = sima.ImagingDataset(sequences, Ch1.sima')

Is it because my file is to heavy ? (1Go)
Thanks
Celia

**Comment by pkaifosh** [comment]
Hi Celia, 
Can you please list all the commands that you entered prior to your issue, all warning messages, and how you determined that the program crashed. Thanks.

The size of your dataset should not be an issue; we analyze datasets at least 10x larger.

One thing to note is that there syntax in what you pasted is wrong (you are missing a quotation mark before Ch1).

**Comment by celialoriette** [comment]
> Hi Celia,
> Can you please list all the commands that you entered prior to your issue,
> all warning messages, and how you determined that the program crashed.
> Thanks.
>
> The size of your dataset should not be an issue; we analyze datasets at
> least 10x larger.
>
> One thing to note is that there syntax in what you pasted is wrong (you
> are missing a quotation mark before Ch1).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/losonczylab/sima/issues/130#issuecomment-75289523

Hi !
Sorry I wasn't here last week...
I entered :import sima
>>> sequences = [sima.Sequence.create('TIFF', 'Ch1.tif')]
>>> dataset = sima.ImagingDataset(sequences, 'Ch1_TIFF.sima')

I am in the folder with Ch1.tiff end when I launched the last command, a
window opens with written : "python stopped functioning"

**Comment by pkaifosh** [comment]
What method did you use to install Python? (Winpython, Anaconda, Python(x,y)?) What version of Python are you using?

How are you running Python? From Spyder? From the command line shell? Is there any other information that you are given when Python crashes?

**Comment by celialoriette** [comment]
> What method did you use to install Python? (Winpython, Anaconda,
> Python(x,y)?) What version of Python are you using?
>
> How are you running Python? From Spyder? From the command line shell? Is
> there any other information that you are given when Python crashes?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/losonczylab/sima/issues/130#issuecomment-76996631


I installed it with Python (x,y) and I am running it from the command line
shell.
Nothing is given to me more than this "python stopped functioning" ...

**Comment by pkaifosh** [comment]
OK. Perhaps the simplest thing would be to try with WinPython instead of Python(x,y). I think I'll move WinPython up above Python(x,y) on the list of recommended installations.

Sorry, I've never seen this issue before and it's hard to figure much out with such limited information.

**Comment by celialoriette** [comment]
> OK. Perhaps the simplest thing would be to try with WinPython instead of
> Python(x,y). I think I'll move WinPython up above Python(x,y) on the list
> of recommended installations.
>
> Sorry, I've never seen this issue before and it's hard to figure much out
> with such limited information.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/losonczylab/sima/issues/130#issuecomment-77174819

Thanks
It's stoned crashing with WinPython... Strange.
I have some  last questions however.
In your tutorial, you add lots of parameter before the roi segmentation as
it follows : segmentation_approach = sima.segment.PlaneCA1PC(
    channel='GCaMP',
    num_pcs=30,
    max_dist=(3, 6),
    spatial_decay=(3, 6),
    cut_max_pen=0.10,
    cut_min_size=50,
    cut_max_size=150,
    x_diameter=14,
    y_diameter=7,
    circularity_threhold=.5,
    min_roi_size=20,
    min_cut_size=40
)
Where can we see which one of these instructions are for? I have only one
channel and never specified it as 'GCaMP', do I have to skip this and not
write "channel=...' ?
At last, I am trying to analyze different videos of the same mouse along
days. What's better : Put all of them in the dataset, will the roi be the
same for all of them ? Or analyze each video separately and then try to
merge the rois ? (with the ROI BUDY isn't it ?)
Thanks and sorry, I am beginner in this kind of programming...

**Comment by pkaifosh** [comment]
Sorry, there was a problem with the website. But it's fixed now and you can view the desired information here:

http://www.losonczylab.org/sima/1.0/api/segment.html

Let us know if you feel it is unclear or incomplete.
