### ISSUE TITLE
Error in extracting masked sequence

### ISSUE THREAD

**Issue by nbdanielson** [losonczylab/sima#131]
I have used a _Masked_Sequence to initialize an imaging dataset.  There are 40 contiguous frames I have masked (so they should all be NaN).  When you call extraction on this dataset, you get an error on line 128 of extract.py.

I believe this is happening because 'imaged_pixels' is all False, as is 'imaged_rois'

@jzaremba how should we handle this case?

**Comment by jzaremba** [comment]
Can you show me the actual error message and the line it failed on? Line 128 isn't related in the version I'm running at the moment.

We can probably just return right away if there are no imaged pixels.

**Comment by jzaremba** [comment]
Let me know if fe98d26bb4a6031641d9c9045b008de1f886fb11 fixes it.

**Comment by nbdanielson** [comment]
awesome, thanks so much for looking into this!  I checkout your branch and will give this a spin right now!

**Comment by nbdanielson** [comment]
just checked the result -- works beautifully.  result shown below for 3 cells:

![capture](https://cloud.githubusercontent.com/assets/8344546/6319568/4f7df6a8-ba8e-11e4-9655-876ab0a4fe30.PNG)
