### ISSUE TITLE
outdated link ROIBuddy

### ISSUE THREAD

**Issue by kassailattice628** [losonczylab/sima#136]
I was struggling to install roibuddy 1.0.0 in my Mac OSX 10.9.5 and finally found the link of rouibuddy source file was outdated (http://www.losonczylab.org/sima/1.0/roi_buddy.html#mac-os-x). After I got a correct source file from PyPI(roibuddy-1.0.0.tar.gz (md5) @ https://pypi.python.org/pypi/roibuddy), and then "sudo python setup.py install" succeeded.

**Comment by pkaifosh** [comment]
Sorry about the confusion and thanks for the report. The website is now updated.
