### ISSUE TITLE
Cannot export motion-corrected frames

### ISSUE THREAD

**Issue by nk53** [losonczylab/sima#138]
The following code:

>import sima
>from sima.motion import PlaneTranslation2D

>analysis_dir = "hmm_test.sima"

>seq = sima.Sequence.create('TIFF', 'original.tif')
>ds = PlaneTranslation2D(max_displacement=[100, 100]).correct([seq], 'pt_test.sima')
>ds.export_frames([[['corrected_pt.tif']]])

Causes the following error:
>Traceback (most recent call last):
>  File "./pt_test.py", line 11, in \<module\>
>    ds.export_frames([[['corrected_pt.tif']]])
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site->packages/sima/imaging.py", line 623, in export_frames
>    if (fmt in ['TIFF16', 'TIFF8']) and not depth(filenames) == 3:
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site->packages/sima/imaging.py", line 622, in depth
>    (not isinstance(L, str)) and max(list(map(depth, L))) + 1
>...
>File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site->packages/sima/imaging.py", line 622, in depth
>    (not isinstance(L, str)) and max(list(map(depth, L))) + 1
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site->packages/sima/imaging.py", line 621, in depth
>    return isinstance(L, collections.Sequence) and \
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 132, >in \_\_instancecheck\_\_
>    if subclass is not None and subclass in cls.\_abc_cache:
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/\_weakrefset.py", >line 72, in \_\_contains\_\_
>    wr = ref(item)
>RuntimeError: maximum recursion depth exceeded

When using the following file original.tif:
https://drive.google.com/file/d/0B5tB6Q_10OpTU0NBeU5mcG01WkE/view?usp=sharing

**Comment by pkaifosh** [comment]
Thanks for the report. I've now fixed the issue in this commit: 5d3e5bf7be55281ad747a46ec50711ba2f4f122f.
