### ISSUE TITLE
Pickling of long arrays?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [losonczylab/sima#157]
There seems to be a problem of pickling a large array (Uint16 (1000L, 800L, 1536L)).

   sequences =[sima.Sequence.create('ndarray', dset[1:1000,:,:])]
   dataset = sima.ImagingDataset(sequences, '20150416_14_10_02_3weeks_3um_XYT'+'.sima',       channel_names=['green'])
'

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-3-0010787ce602> in <module>()
      1 sequences =[sima.Sequence.create('ndarray', dset[1:1000,:,:])]
----> 2 dataset = sima.ImagingDataset(sequences, '20150416_14_10_02_3weeks_3um_XYT'+'.sima', channel_names=['green'])

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\site-packages\sima\imaging.pyc in __init__(self, sequences, savedir, channel_names, read_only)
    145                     str(x) for x in range(self.frame_shape[-1])]
    146             else:
--> 147                 self.channel_names = channel_names
    148         else:
    149             raise TypeError('ImagingDataset objects must be initialized '

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\site-packages\sima\imaging.pyc in channel_names(self, names)
    227         self._channel_names = [str(n) for n in names]
    228         if self.savedir is not None and not self._read_only:
--> 229             self.save()
    230 
    231     @property

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\site-packages\sima\imaging.pyc in save(self, savedir)
    743         sequences = [seq._todict(savedir) for seq in self.sequences]
    744         with open(join(savedir, 'sequences.pkl'), 'wb') as f:
--> 745             pickle.dump(sequences, f, pickle.HIGHEST_PROTOCOL)
    746 
    747         with open(join(savedir, 'dataset.pkl'), 'wb') as f:

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in dump(obj, file, protocol)
   1368 
   1369 def dump(obj, file, protocol=None):
-> 1370     Pickler(file, protocol).dump(obj)
   1371 
   1372 def dumps(obj, protocol=None):

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in dump(self, obj)
    222         if self.proto >= 2:
    223             self.write(PROTO + chr(self.proto))
--> 224         self.save(obj)
    225         self.write(STOP)
    226 

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save(self, obj)
    284         f = self.dispatch.get(t)
    285         if f:
--> 286             f(self, obj) # Call unbound method with explicit self
    287             return
    288 

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save_list(self, obj)
    598 
    599         self.memoize(obj)
--> 600         self._batch_appends(iter(obj))
    601 
    602     dispatch[ListType] = save_list

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in _batch_appends(self, items)
    634                 write(APPENDS)
    635             elif n:
--> 636                 save(tmp[0])
    637                 write(APPEND)
    638             # else tmp is empty, and we're done

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save(self, obj)
    284         f = self.dispatch.get(t)
    285         if f:
--> 286             f(self, obj) # Call unbound method with explicit self
    287             return
    288 

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save_dict(self, obj)
    647 
    648         self.memoize(obj)
--> 649         self._batch_setitems(obj.iteritems())
    650 
    651     dispatch[DictionaryType] = save_dict

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in _batch_setitems(self, items)
    679                 for k, v in tmp:
    680                     save(k)
--> 681                     save(v)
    682                 write(SETITEMS)
    683             elif n:

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save(self, obj)
    329 
    330         # Save the reduce() output and finally memoize the object
--> 331         self.save_reduce(obj=obj, *rv)
    332 
    333     def persistent_id(self, obj):

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save_reduce(self, func, args, state, listitems, dictitems, obj)
    417 
    418         if state is not None:
--> 419             save(state)
    420             write(BUILD)
    421 

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save(self, obj)
    284         f = self.dispatch.get(t)
    285         if f:
--> 286             f(self, obj) # Call unbound method with explicit self
    287             return
    288 

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save_tuple(self, obj)
    560         write(MARK)
    561         for element in obj:
--> 562             save(element)
    563 
    564         if id(obj) in memo:

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save(self, obj)
    284         f = self.dispatch.get(t)
    285         if f:
--> 286             f(self, obj) # Call unbound method with explicit self
    287             return
    288 

C:\Users\maximih\AppData\Local\Continuum\Anaconda\lib\pickle.pyc in save_string(self, obj, pack)
    484                 self.write(SHORT_BINSTRING + chr(n) + obj)
    485             else:
--> 486                 self.write(BINSTRING + pack("<i", n) + obj)
    487         else:
    488             self.write(STRING + repr(obj) + '\n')

error: integer out of range for 'i' format code

**Comment by pkaifosh** [comment]
Here is some discussion about the cause of this bug.

http://stackoverflow.com/questions/28503942/pickling-large-numpy-array

Probably the best way for us to address this is to use numpy.save() or numpy.savez().
