### ISSUE TITLE
Strange Qt error with ROI buddy

### ISSUE THREAD

**Issue by MaximilianHoffmann** [losonczylab/sima#158]
Hi Again,

When launching ROIbuddy script: NameError: global name 'QString' is not defined

I am definitely running Python 2.7 (WinPython) , so its supposed to be there (I read, that with Python 3.0 , it should be subsummed into Qvariant). However:

http://lists.osgeo.org/pipermail/qgis-developer/2014-April/032126.html

Indeed, just taking str() instead of Qstring works, so maybe it has something to do with SIP.

Stacktrace:

 runfile('C:/Users/maximih/AppData/Local/WinPython-64bit-2.7.9.4/python-2.7.9.amd64/Lib/site-packages/ROIBuddy/roi_buddy.py', wdir='C:/Users/maximih/AppData/Local/WinPython-64bit-2.7.9.4/python-2.7.9.amd64/Lib/site-packages/ROIBuddy')
C:\Users\maximih\AppData\Local\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\skimage\filter\__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\maximih\AppData\Local\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)
  File "C:\Users\maximih\AppData\Local\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/maximih/AppData/Local/WinPython-64bit-2.7.9.4/python-2.7.9.amd64/Lib/site-packages/ROIBuddy/roi_buddy.py", line 2246, in <module>
    main()
  File "C:/Users/maximih/AppData/Local/WinPython-64bit-2.7.9.4/python-2.7.9.amd64/Lib/site-packages/ROIBuddy/roi_buddy.py", line 2241, in main
    form = RoiBuddy()
  File "C:/Users/maximih/AppData/Local/WinPython-64bit-2.7.9.4/python-2.7.9.amd64/Lib/site-packages/ROIBuddy/roi_buddy.py", line 173, in __init__
    self.define_actions()
  File "C:/Users/maximih/AppData/Local/WinPython-64bit-2.7.9.4/python-2.7.9.amd64/Lib/site-packages/ROIBuddy/roi_buddy.py", line 266, in define_actions
    icon=QIcon(QString(os.path.join(icon_filepath,"document-save-5.png"))),
NameError: global name 'QString' is not defined

pip freeze:

astroid==1.3.6
backports.ssl-match-hos
baresql==0.7.1
beautifulsoup4==4.3.2
brewer2mpl==1.4.1
certifi==14.5.14
cffi==0.9.2
colorama==0.3.3
configparser==3.5.0b2
cvxopt==1.1.7
cx-Freeze==4.3.4
Cython==0.22
db.py==0.4.1
decorator==3.4.2
docutils==0.12
enum34==1.0.4
fonttools==2.4
formlayout==1.0.15
funcsigs==0.4
future==0.14.3
ggplot==0.6.5
guidata==1.6.1
guiqwt==2.3.1
h5py==2.4.0
husl==4.0.1
ipython==3.0.0
ipython-sql==0.3.5
Jinja2==2.7.3
joblib==0.8.4
jsonschema==2.4.0
julia==0.1.1.8
llvmlite==0.2.2
lmfit==0.8.3
logilab-common==0.63.2
logutils==0.3.3
lxml==3.4.2
mahotas==1.2.4
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.5.1
mpld3==0.2
mysql-connector-python=
networkx==1.9.1
nltk==3.0.2
nose==1.3.4
numba==0.17.0
numexpr==2.4
numpy==1.9.2
numpydoc==0.5
oct2py==3.1.0
pandas==0.16.0
patsy==0.3.0
pep8==1.6.2
pg8000==1.10.1
Pillow==2.7.0
Polygon2==2.0.7
prettytable==0.7.2
psutil==2.2.1
PuLP==1.5.6
pybars3==0.9.1
pycparser==2.10
pyflakes==0.8.1
Pygments==2.0.2
pyhdf==0.8.3
pylint==1.4.3
PyMeta3==0.5.1
pyodbc==3.0.7
PyOpenGL==3.1.0
pyparsing==2.0.3
PyQt4==4.11.3
PyQtdesignerplugins==1.
PyQwt==5.2.1
pyserial==2.7
python-dateutil==2.4.0
pytz==2015.2
pywin32==219
PyYAML==3.11
pyzmq==14.5.0
reportlab==3.1.44
requests==2.6.0
roibuddy==1.0.0
rope==0.10.2
rpy2==2.5.6
runipy==0.1.3
scikit-image==0.11.2
scikit-learn==0.16.0
scilab2py==0.6
scipy==0.15.1
seaborn==0.5.1
Shapely==1.5.7
sima==1.1.1
simplejson==3.6.5
singledispatch==3.4.0.3
six==1.9.0
spyder==2.3.4
SQLAlchemy==0.9.9
sqlite-bro==0.8.7.4
sqlparse==0.1.14
statsmodels==0.6.1
sympy==0.7.6
tables==3.1.1
tornado==4.1
tqdm==1.0
TTFQuery==1.0.5
ViTables==2.1
VPython==5.74
wheel==0.24.0
winpython==1.1
xlrd==0.9.3
XlsxWriter==0.7.1

**Comment by nbdanielson** [comment]
in an ipython shell, you should be able to run the following if you have
the PyQt dependency installed correctly

from PyQt4.QtCore import *

str = QString('testing')

**Comment by MaximilianHoffmann** [comment]
Dear Nathan,

my QtCore does not have a QString attribute. Doesnt show up. Everything 
else, QVariant etc... is.
I usually work under Unix and the python environments on windows seem to 
easily screw everything up...so not sure whether the problem is on my 
side.

Many Thanks
Max

Am 20.04.2015 17:32 schrieb Nathan Danielson:
> in an ipython shell, you should be able to run the following if you
> have
>  the PyQt dependency installed correctly
> 
>  from PyQt4.QtCore import *
> 
>  str = QString('testing')
> 
>  On Mon, Apr 20, 2015 at 10:42 AM, MaximilianHoffmann <

**Comment by nbdanielson** [comment]
No problem, good luck!

**Comment by jzaremba** [comment]
I've recently done clean installs of ROIBuddy on Windows using Christoph Gohlke's pre-built wheels that worked fine.

What versions on Qt and SIP are you using?
https://wiki.python.org/moin/PyQt/Getting%20the%20version%20numbers%20of%20Qt,%20SIP%20and%20PyQt

**Comment by MaximilianHoffmann** [comment]
Thanks, I am using:

('Qt version:', '4.8.6')
('SIP version:', '4.16.4')
('PyQt version:', '4.11.3')

This is what comes with the last build of Winpython. I'd like to use 
Python(x,y), but I dont have currently admin rights on this PC and it 
seemed, that you need them for Python(x,y).
With Anaconda, I had a huge qt problem in the first place....

Best
Max

Am 20.04.2015 20:42 schrieb Jeff Zaremba:

**Comment by MaximilianHoffmann** [comment]
ok, the issue was: I cant start the standalone exe, because it errors: "Cannot create process with pythonw.exe" , so I tried to execute the python scipts in spyder. spyder by default sets the sip,api for Qstring to v2 , but this code needs v1. S. http://pyqt.sourceforge.net/Docs/PyQt4/incompatible_apis.html

Unfortunately the problem for the exe remains, executing the script I find that the GUI freezes upon importing a SIMA folder, but this is maybe something for a different issue,
