### ISSUE TITLE
Error when opening sima1.2.0 generated datasets with roi_buddy

### ISSUE THREAD

**Issue by ThomasHainmueller** [losonczylab/sima#168]
I recently updated sima to version to 1.2.0. Now I have a problem when trying to open any *.sima dataset in roi_buddy that has been generated since the update. Datasets that have been stored before can be loaded without any issue. The ROI_Buddy.exe.log. appends the following error message whenever I try to open a "new" *.sima file:

Traceback (most recent call last):
  File "roi_buddy.py", line 560, in add_tseries
  File "roi_buddy.py", line 1397, in __init__
  File "sima\imaging.pyo", line 306, in load
  File "sima\imaging.pyo", line 130, in __init__
ImportError: No module named future.types.newstr

I have future 0.14.3 installed and '''import future.types.newstr''' works w.o. problems from the python console. Also, I can't find any reference to future.types.newstr in neither imaging.py, nor roi_buddy.py. Can you help?

Thanks in advance and best greetings
Thomas

**Comment by nbdanielson** [comment]
Hi Thomas,
Thanks for the report.  To confirm, if you are in the Python console, you
can load the dataset with no problems using the
ImagingDataset.load('/path/to/sima/dir') command?

**Comment by ThomasHainmueller** [comment]
yes, everything from within sima works fine. I can load the datasets, export frames and see the attributes. The problem seems to be between the new ImagingDataset type and the ROI_buddy (V. 1.0.0). Thx for the fast reply!

**Comment by nbdanielson** [comment]
This might be a problem with the .exe.  Can you try running ROI Buddy from
source (e.g. forking from the github repo and then running 'python
roi_buddy.py')?
Best,
Nathan

**Comment by ThomasHainmueller** [comment]
Yes, this was indeed the problem! I built roibuddy from source and now i can open datasets generated by sima 1.2.0. Thanks a lot Nathan!

There is still one problem though: When generating ROIs with the STICA method and trying to open those in roibuddy, i get the following error in the console:

Traceback (most recent call last):
File "roi_buddy.py", line 921, in toggle_rois
active_tSeries.initialize_rois()
File "roi_buddy.py", line 1918, in initialize_rois
for poly in roi.coords:
File "C:\Python27\lib\site-packages\sima\ROI.py", line 231, in coords
for polygon in self.polygons:
File "C:\Python27\lib\site-packages\sima\ROI.py", line 220, in polygons
'Unable to convert a non-boolean mask to polygons')
sima.ROI.NonBooleanMask: Unable to convert a non-boolean mask to polygons

Is there any solution allready to convert the polygon-ROIs of STICA to boolean masks?

Thanks and best greetings
Thomas

**Comment by nbdanielson** [comment]
Hi Thomas,
Happy to hear that worked!

Regarding the STICA-generated ROIs -- I believe Jack has been working some functionality for converting these to polygons -- @jbowler06 can you weigh in here?

**Comment by neurodroid** [comment]
> Is there any solution allready to convert the polygon-ROIs of STICA to boolean masks?

Yes, using one of the [postprocessing steps](http://www.losonczylab.org/sima/1.2/api/segment.html#post-processing-steps):
```python
import sima
import sima.segment
import sima.misc
from shutil import copy, copytree

copytree(sima.misc.example_data(), 'example.sima')
copy(sima.misc.example_tiff(), 'example.tif')

dataset = sima.ImagingDataset.load('example.sima')

stica_sparse_approach = sima.segment.STICA(components=19, verbose=True)
stica_sparse_approach.append(sima.segment.SparseROIsFromMasks())
stica_sparse_rois = dataset.segment(stica_sparse_approach, 'stica_sparse_ROIs')

for roi in stica_sparse_rois:
    print(roi.polygons)
```

**Comment by pkaifosh** [comment]
@neurodroid posted this a while back. I'm not sure why it isn't visible anymore.

> Yes, using one of the postprocessing steps:
> 
> import sima
> import sima.segment
> import sima.misc
> from shutil import copy, copytree
>
> copytree(sima.misc.example_data(), 'example.sima')
> copy(sima.misc.example_tiff(), 'example.tif')
>
> dataset = sima.ImagingDataset.load('example.sima')
>
> stica_sparse_approach = sima.segment.STICA(components=19, verbose=True)
> stica_sparse_approach.append(sima.segment.SparseROIsFromMasks())
> stica_sparse_rois = dataset.segment(stica_sparse_approach, 'stica_sparse_ROIs')
> 
> for roi in stica_sparse_rois:
>     print(roi.polygons)

The relevant docs are here: http://losonczylab.org/sima/api/segment.html#post-processing-steps
