### ISSUE TITLE
documentation bugs

### ISSUE THREAD

**Issue by eflister** [losonczylab/sima#179]
http://www.losonczylab.org/sima/1.2/tutorial.html#numpy-arrays
creates dataset with num_sequences=2, frame_shape=(128, 256), num_frames=200
frame_shape is (num_planes, num_rows, num_columns, num_channels)
so, eg segment: ValueError: This segmentation strategy requires a dataset with exactly one plane.

http://www.losonczylab.org/sima/1.2/tutorial.html#automated-segmentation
text says stica, code uses ca1pc

when copy/pasting from http://www.losonczylab.org/sima/1.2/api/index.html
SyntaxError: Non-ASCII character '\xe2' ..., but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
examples: 
http://www.losonczylab.org/sima/1.2/api/sequence.html#sima.Sequence.create
dim_order single quotes
http://www.losonczylab.org/sima/1.2/api/segment.html#sima.segment.STICA
dash between parameter names and descriptions

**Comment by pkaifosh** [comment]
@eflister I've fixed the first two issues here, but I'm having trouble with the third. Can you please provide more detail here. What exactly are you trying to do? What goes wrong? How do you propose fixing it? Thanks.

**Comment by eflister** [comment]
copy pasting that doc into comments in one's code causes a syntax error because of the non-ascii characters.  doc that can be copy/pasted into comments is most useful.

**Comment by eflister** [comment]
trying to segment the dataset from the updated ndarray example now results in the same error as https://github.com/losonczylab/sima/issues/177

**Comment by pkaifosh** [comment]
@eflister Since the doc's are generated by sphinx, I'm not sure if there is a simple solution here. However, sphinx generates the docs from the original plain-text docs in our source code, so you could just copy the docs from the original .py files.

**Comment by eflister** [comment]
ok, thanks, i'd call it a sphinx bug then

**Comment by eflister** [comment]
is sphinx also responsible for the confusion between max_pen and cut_max_pen?
http://www.losonczylab.org/sima/1.2/api/segment.html#ca1-pyramidal-cells
http://www.losonczylab.org/sima/1.2/api/segment.html#normalized-cuts

**Comment by pkaifosh** [comment]
@eflister Can you please be a bit more clear about what you find confusing with these parameters?

**Comment by eflister** [comment]
the parameter docs list a parameter called `max_pen`, but the real name seems to be `cut_max_pen`, as stated in the definition and your examples.
