### ISSUE TITLE
HDF5 doesn't load to proper dim_order

### ISSUE THREAD

**Issue by eflister** [losonczylab/sima#181]
https://github.com/losonczylab/sima/issues/177#issuecomment-107739860
https://github.com/losonczylab/sima/issues/177#issuecomment-107743558

**Comment by jzaremba** [comment]
The example h5 file is the correct shape ('yxt') as stated in the docs. I'm not sure what Matlab is doing there.
```python
In [1]: import sima

In [2]: import h5py

In [3]: f = h5py.File(sima.misc.example_hdf5())

In [4]: f['imaging'].shape
Out[5]: (128, 256, 20)
```

**Comment by eflister** [comment]
huh!  looks like you're right, sorry!

in matlab:
```
>> size(data)

ans =

    10    20   100

>> save('data7.3','data','-v7.3')
>> h5create('data.h5','/data',size(data))
>> h5write('data.h5','/data',data)
```

in python:
```
>>> import h5py
>>> h5py.File('data7.3')['data'].shape
(100, 20, 10)
>>> h5py.File('data.h5')['data'].shape
(100, 20, 10)
```

**Comment by jzaremba** [comment]
No worries, that is strange.

**Comment by eflister** [comment]
hrmph - http://stackoverflow.com/questions/21624653/python-created-hdf5-dataset-transposed-in-matlab addresses it.  may be useful to your users to warn them about this -- do you not have throngs of matlab refugees arriving on shanty boats?

**Comment by pkaifosh** [comment]
@eflister Perhaps you could write a little section of tips for MATLAB users that we can add to the docs once you are done with #183 ?
