### ISSUE TITLE
feature request: be importable into matlab's python interface

### ISSUE THREAD

**Issue by eflister** [losonczylab/sima#183]
our lab works in matlab.  we can interoperate with sima by writing to disk, but our datasets are large (~1 hour recordings, several GB of ~256x256 frames at ~3hz, and we'll have resonant scanning datasets soon (10x higher framerate).  it would be nicer and faster to interoperate w/sima in memory.  

as discussed in [this thread starting here](https://github.com/losonczylab/sima/issues/178#issuecomment-107814772) matlab has a [python interface](http://www.mathworks.com/help/matlab/call-python-libraries.html) that facilitates in-memory communication.  as shown there, sima's dependencies import fine into matlab, but sima doesn't for some reason.  i've asked mathworks (waiting for response) and [SO](http://stackoverflow.com/questions/30605179/why-cant-matlab-import-this-python-library).

once we can import sima, the following shows it's possible to initialize a numpy.ndarray with a matlab array, and then convert back.  two annoying limitations are that we have to go through array.array, and have to flatten to 1D for each direction of transfer, but these could be hidden in some conversion functions.  can anyone find a better way?

in matlab:
```
>> whos('x')
  Name      Size             Bytes  Class     Attributes

  x         2x3x4              192  double              

>> reshape(double(py.array.array('d',py.numpy.array(x(:)'))),size(x)) == x

ans(:,:,1) =

     1     1     1
     1     1     1


ans(:,:,2) =

     1     1     1
     1     1     1


ans(:,:,3) =

     1     1     1
     1     1     1


ans(:,:,4) =

     1     1     1
     1     1     1
```

an alternative would be to [go the other way](http://www.mathworks.com/help/matlab/matlab-engine-for-python.html), but we're just more comfortable in matlab and have a ton of exisitng infrastructure.

**Comment by pkaifosh** [comment]
@eflister This is an interesting idea potentially helpful to many people, although beyond the scope of our current priorities. As well, we are not running MATLAB on our lab's server and would not be able to test any changes made. If this is of strong interest to you, you are more than welcome to figure out what the issues are and submit any pull requests to make the necessary changes required. I think progress on this issue would be better if the work were carried out by someone actually using MATLAB. I'll assign this issue to you, and leave you with the decision about how to proceed.

**Comment by eflister** [comment]
progress -- i devised a (tedious) method to isolate the problematic imports and updated the [SO post](http://stackoverflow.com/questions/30605179/why-cant-matlab-import-this-python-library) with new findings.

summary -- here are (at least most of the) problems:
```
from PIL import Image

from skimage.measure import approximate_polygon
from skimage.measure import find_contours
from skimage.filter import threshold_otsu
from skimage import transform as tf

from sklearn.decomposition import FastICA

import scipy.io
from scipy.stats import uniform
from scipy.linalg import inv
from scipy.sparse.linalg import eigsh, eigs
from scipy.sparse.linalg import inv
from scipy import ndimage
from scipy.ndimage import measurements

import cv2

note the following are OK:
from scipy.linalg import eig, eigh, norm
from scipy import sparse
from multiprocessing import Pool
import multiprocessing.util as util
```

unfortunately, it looks like it would be pretty hard for sima to live without these -- let me know if i'm wrong.

the trouble mainly seems to be matlab's libtiff.5.dylib (PIL and opencv require later version) and libgfortran.3.dylib (doesn't work for scipy's _lbfgsb.so, _ufuncs.so, _arpack.so).  perhaps PIL/opencv/scipy could be compiled against matlab's libraries somehow?  that kind of thing is outside of my experience...

**Comment by eflister** [comment]
yay, major progress!  forcing matlab to use the libraries that python compiles against allows the imports!
```
~$ DYLD_INSERT_LIBRARIES=/opt/local/lib/libgcc/libgfortran.3.dylib:/opt/local/lib/libtiff.5.dylib /Applications/MATLAB_R2015a.app/bin/matlab
```
not sure of the equivalent for windows, on linux i think it's `LD_PRELOAD`

unfortunately something goes wrong with the actual call to `sima.Sequence.create()` -- any ideas here?
```
>> import py.sima
Error using import
Import argument 'py.sima' cannot be found or cannot be imported.

>> import py.sima.Sequence % succeeds!
>> import py.sima.ImagingDataset % succeeds!
>> x = py.sima.ImagingDataset([1,2],'~')
Python Error: ImagingDataset objects must be initialized with a list of sequences.

>> x = py.numpy.random.random([2,3,4])

x = 

  Python ndarray with properties:

           T: [1x1 py.numpy.ndarray]
        base: [1x1 py.NoneType]
      ctypes: [1x1 py.numpy.core._internal._ctypes]
        data: [1x192 py.buffer]
       dtype: [1x1 py.numpy.dtype]
       flags: [1x1 py.numpy.flagsobj]
        flat: [1x1 py.numpy.flatiter]
        imag: [1x1 py.numpy.ndarray]
    itemsize: 8
      nbytes: 192
        ndim: 3
        real: [1x1 py.numpy.ndarray]
       shape: [1x3 py.tuple]
        size: 24
     strides: [1x3 py.tuple]

    [[[ 0.4158531   0.18912596  0.20743597  0.92631168]
      [ 0.0371785   0.48093953  0.88221637  0.85687334]
      [ 0.2267605   0.79464779  0.97438662  0.47791076]]

     [[ 0.05602249  0.06596678  0.05691491  0.02706325]
      [ 0.28477145  0.74781928  0.56700236  0.14500885]
      [ 0.87999554  0.78932748  0.24473039  0.18383564]]]

>> x = py.sima.Sequence.create('ndarray',x)
The class "py.sima.Sequence" is undefined.
Perhaps Java is not running.

>> py.sima.segment.STICA()

ans = 

  Python STICA with no properties.

    <sima.segment.stica.STICA object at 0x138e15890>

>> py.sima.segment.PlaneCA1PC()

ans = 

  Python PlaneCA1PC with no properties.

    <sima.segment.ca1pc.PlaneCA1PC object at 0x138e158d0>
```

**Comment by eflister** [comment]
doesn't look as easy on windows: http://en.wikipedia.org/wiki/DLL_injection#Approaches_on_Microsoft_Windows
http://stackoverflow.com/questions/1178257/ld-preload-equivalent-for-windows-to-preload-shared-libraries

**Comment by eflister** [comment]
this is interesting.  `h5py` is throwing `ImportError`:

```
>> import py.h5py
Error using import
Import argument 'py.h5py' cannot be found or cannot be imported.
 
>> py.importlib.import_module('h5py')
Python Error: cannot import name _errors
```

and indeed, `h5py_available` is `0`, but the capitalization is unexpected.  but using the same capitalization doesn't help `sima.Sequence.create()` -- what's going on???

```
>> c = py.sima.Sequence.h5py_available
The class "py.sima.Sequence" is undefined.
Perhaps Java is not running.
 
>> c = py.sima.sequence.h5py_available

c =

     0
 
>> x = py.sima.Sequence.create('ndarray',x)
The class "py.sima.Sequence" is undefined.
Perhaps Java is not running.
 
>> x = py.sima.sequence.create('ndarray',x)
Undefined variable "py" or class "py.sima.sequence.create".
```

**Comment by eflister** [comment]
aha -- it's the leading underscores for attributes of `sima.Sequence`, which matlab [doesn't allow](http://www.mathworks.com/help/matlab/matlab_external/limitations-to-python-support.html):
```
>> py.sima.Sequence
Python Error: Can't instantiate abstract class Sequence with abstract methods _get_frame, _todict
```

but as long as we don't touch a `Sequence` directly in matlab, we're golden!  :)  finally sweet success!

`tosimainmem.py`:
```
#! /usr/bin/env python

import sima
import sima.segment

import numpy as np

def seg(d):

    dataset_path = 'dataset.sima' 

    # premute to numpy array (num_frames, num_planes, num_rows, num_columns, num_channels)
    d = np.transpose(d, (2, 0, 1)) # equiv to np.rollaxis(d,2), which might be more efficient?
    d = d[:, np.newaxis, :, :, np.newaxis] # could use np.expand_dims() or np.reshape()

    # feature request: dim_order = 'yxt' https://github.com/losonczylab/sima/issues/178
    seq = sima.Sequence.create('ndarray', d)

    dataset = sima.ImagingDataset([seq], dataset_path)
    segmentation_approach = sima.segment.STICA()

    rois = dataset.segment(segmentation_approach, 'auto_ROIs')
    # masks are (z, y, x), (plane, row, column)

    def compose(f,g): return lambda x: f(g(x))

    if len(rois) > 0:
        # float64's -- some segment methods are binary, others soft
        masks = np.dstack(map(compose(np.squeeze, np.array), rois)) 
    else:
        masks = np.empty(0)

    return masks
```

```
>> rois = py.tosimainmem.seg(py.numpy.random.random([10,20,100]))
rois = 

  Python ndarray with properties:

           T: [1x1 py.numpy.ndarray]
        base: [1x1 py.NoneType]
      ctypes: [1x1 py.numpy.core._internal._ctypes]
        data: [1x120000 py.buffer]
       dtype: [1x1 py.numpy.dtype]
       flags: [1x1 py.numpy.flagsobj]
        flat: [1x1 py.numpy.flatiter]
        imag: [1x1 py.numpy.ndarray]
    itemsize: 8
      nbytes: 120000
        ndim: 3
        real: [1x1 py.numpy.ndarray]
       shape: [1x3 py.tuple]
        size: 15000
     strides: [1x3 py.tuple]

    [[[ -6.17023064e-04   1.81946596e-03  -1.55426273e-03 ...,   2.00455467e-03
        -1.75934080e-03  -8.92923708e-04]
      [ -7.23126361e-04   3.44713103e-04   3.38801182e-04 ...,   5.99991170e-04
         1.07861995e-03  -8.76782074e-04]
      [ -9.54703065e-04  -2.49369453e-04   2.30911194e-04 ...,   1.48956889e-03
         1.46368358e-03  -5.54195980e-04]
  <snip>
      [ -1.27150309e-03   2.73796205e-04  -1.58290114e-04 ...,   1.68862001e-04
        -1.51119283e-03   1.41239389e-04]
      [ -2.64029203e-03  -1.49572599e-03  -1.62806689e-03 ...,   5.47074965e-04
         7.80112074e-04  -1.16478656e-03]
      [  3.58641939e-04  -7.94447441e-04  -1.48526258e-03 ...,  -1.08458510e-03
        -5.67736529e-05   1.30724644e-04]]]

>> rois.shape

ans = 

  Python tuple with no properties.

    (10, 20, 75)
```

**Comment by eflister** [comment]
interesting -- on windows the problem didn't seem to be `libtiff` or `libgfortran`.  i extracted all the `import` lines in `sima` source and ran `matlab`'s `py.importlib.import_module()` on each, the only problems were the same `h5py` issue and this for `shapely.geometry`:
```
  PyException with properties:

    ExceptionObject: [1x3 py.tuple]
         identifier: 'MATLAB:Python:PyException'
            message: 'Python Error: [Error 1114] A dynamic link library (DLL) initialization routine failed'
              cause: {}
              stack: [1x1 struct]
```
i know `sima` requires a special windows build of `shapely` form [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely), and that's what i use (everything runs fine in python).  i haven't looked into why -- do you guys know?  could this explan the `matlab` problem?  how well could sima's ROI work without `shapely`?

**Comment by eflister** [comment]
it came up during this search that i'm not getting `pyfftw`, which it looks like `align.py` could benefit from these.  it looks like it's available on pypi -- any reason you don't include it in your dependencies?

**Comment by pkaifosh** [comment]
We did not include ```pyfftw``` as a dependency since it requires separate installation of FFTW. We should add it to our list of optional dependencies though, since it does make alignment run faster.

**Comment by eflister** [comment]
aha - on windows, the problem is not in libgfortran/libtiff, but with shapely's use of msvcr. winpython uses msvcr90.dll, but matlab uses msvcr100.dll. in shapely, replacing CDLL(find_library('c')) with CDLL('C:\\Program Files\\MATLAB\\R2015a\\bin\\win64\\msvcr100.dll') makes it all work. http://stackoverflow.com/questions/27389227/how-do-i-load-a-c-dll-from-the-sxs-in-python seems to be a method that would determine that path automatically, appropriate for wherever you are invoking shapely from.

**Comment by eflister** [comment]
and the shapely devs realized `ctypes.cdll.msvcrt` works -- even better, don't have to do fancy stuff to figure out the right path.  `uuid`, which sima imports somewhere, has the same problem, but from within a try block, so altho the error window pops up, it only happens once and is recovered from.

**Comment by pkaifosh** [comment]
I'm closing this issue. If there is something specific that needs to change in SIMA, a new issue can be created.
