### ISSUE TITLE
feature request: refer to channels by name

### ISSUE THREAD

**Issue by eflister** [losonczylab/sima#186]
the channels get names, but most api calls refer to them by index.  to eliminate the possibility of those getting out of sync, have the option to use names.

**Comment by eflister** [comment]
ah well i guess `workflow.py` shows you can use the name at least sometimes, but the doc typically says they should be `int`, eg: [here](http://www.losonczylab.org/sima/1.2/api/segment.html#ca1-pyramidal-cells)

**Comment by pkaifosh** [comment]
@eflister Are you interested in adjusting the docs for this issue and submitting a pull request? If so, I'll assign the issue to you.

**Comment by eflister** [comment]
er...  find every instance and verify whether it's true, i realize it's not trivial.  you guys want the docs to be accurate tho right?  does sphynx provide/integrate into some kind of input validation/type verification framework that would automate this and keep it accurate?  i find this aspect of dynamic languages galling and have a policy of not manually doing automatable tasks :)

**Comment by pkaifosh** [comment]
I am not aware of any such type verification in Sphynx.
