### ISSUE TITLE
Support for I/O with Amazon S3

### ISSUE THREAD

**Issue by vjlbym** [losonczylab/sima#189]
Hi SIMA developers,

Thanks a lot for putting together this package. It is proving to be really helpful. Recently, our lab has been dealing with relatively large datasets for which motion correction is very slow. So we're trying to run SIMA on individual machines on Amazon EC2 to get a parallel workflow going. I've managed to load data in from a public bucket in S3 by 
```
import urllib
import cStringIO
filetoread = cStringIO.StringIO(urllib.urlopen(URL).read())
sequences = [sima.Sequence.create('TIFF', filetoread)]
```
This code, as things stand, doesn't work since SIMA expects a local path as argument for the file path. So I got it to work by just changing line 460 of sequence.py from `abspath(path)` to `path`. I understand that this is somewhat ill-advised due to the lack of error catching, but it does work.

The thing is, I'd also like to get SIMA to output the data to S3, preferably using boto. As things stand, I can output the data to a local filesystem on EBS and then copy over to S3. But this is somewhat inefficient. So I was hoping that someone could help me with this. It'd be great if this is built in to SIMA. 

Also, is the algorithm written to use all available cores on a computer or is it purely serial?

Thanks a lot for your help and SIMA!

Vijay
Stuber lab, UNC-CH

**Comment by pkaifosh** [comment]
Hi Vijay,

What is the precise problem that you run into when trying to output the data directly to S3? What would need to be changed to fix this?

**Comment by vjlbym** [comment]
Hi Patrick,

I was initially thinking that I could try to set up SIMA to do all file write operations to S3 as a way of cost-cutting on storage but I see that this would be quite non-trivial. So I guess I am good. Thanks for your help!

Btw, I have an unrelated question I was hoping you could help with. I see that SIMA uses only a single vCPU per script. Do you know if I can run SIMA on 4 different data sets simultaneously to use 4 different available vCPUs?

I'll mark the issue closed after this. Thanks again!

**Comment by pkaifosh** [comment]
In our lab, we just run multiple Python jobs, each running SIMA on a different dataset. Is there any reason why that wouldn't work for you?

**Comment by vjlbym** [comment]
I don't think so. Just wanted to make sure that it's designed to run that way. Thanks a lot, Patrick!
