### ISSUE TITLE
"Failed to estimate positive gains"

### ISSUE THREAD

**Issue by vjlbym** [losonczylab/sima#195]
Hi,

I've been trying to get SIMA to run motion correction on a 5 gb video acquired with a 2P microscope using resonant scanning at 2.5 Hz for 2 hours. I am running it on a really beefed up computer on Amazon EC2, which has about 64 gb of RAM. I've been getting an error saying "Failed to estimate positive gains". I understand that this is a step involving the calculation of expected photon count to pixel intensity. I've not gotten such an error on many other files that I've run, all of which are considerably smaller than this file. Could you guys please let me know what the issue is? Does it have to do with the file size?

Also, is the motion correction tuned to work better for galvo scan compared to resonant scans on a 2P scope?

Thanks a lot!
Vijay

**Comment by vjlbym** [comment]
Btw, I could provide access to the data in case you need it to reproduce the error. Since it was an error that's handled in the code, I was wondering if there is a simple reason for it.

**Comment by pkaifosh** [comment]
Nothing comes to mind immediately that would cause this issue. Have you used pdb/pudb to try to get a sense of what might be the issue? Perhaps inspecting some of the variables used to calculate the invalid value would give a clue.

Regarding resonant vs. galvos, it may very well be that different parameters are needed for each case. In particular, note that there is a specific motion correction strategy that you should use if you are doing resonant imaging: http://losonczylab.org/sima/1.3/api/motion.html#sima.motion.ResonantCorrection
This strategy takes into consideration the fact that when scanning in opposite directions, the sampling is not equivalent.

**Comment by vjlbym** [comment]
Thanks @pkaifosh for your reply! I haven't yet run any debugging on it. I'll look into that. Thanks! 

And thanks for the comment regarding resonant scanning!

**Comment by vjlbym** [comment]
I just figured out that the issue is that the data did not load correctly. I haven't yet figured out what the issue is, though.
I used `sequences = sima.sequences.create(`TIFF`,<path>)` and it treated this tiff stack as a single image tiff file, or at least, loaded in only one frame. ImageJ loads it in fine. I've tried two files, one that is 5 gb and another that is 12gb and they both fail to import more than one frame.

One thing to note is that this file was concatenated in imagej from individual tiff stacks. I can load in each of those tiff stacks without any problem. But when I load the concatenated ones, even though imageJ stores it as a tif stack, SIMA fails to import more than one frame.

Any clues what might be up?

Thanks!

**Comment by nbdanielson** [comment]
So this is a single multipage TIFF file containing your data?  In that case, you should specify the format as 'TIFFs', rather than 'TIFF' (http://www.losonczylab.org/sima/1.3/api/sequence.html#sima.Sequence.create)

**Comment by nbdanielson** [comment]
what is the output of sequence.shape?

**Comment by vjlbym** [comment]
I see in the documentation that a single multipage TIFF should be formatted as 'TIFF' and not 'TIFFs'. So I have been sticking to that. Is that not correct? The shape is (1,1,512,512,1). Only 1 frame is imported.

**Comment by nbdanielson** [comment]
Yes 'TIFF' is correct (sorry my previous comment was mistaken).  Is there somewhere you could host a reduced dataset we could take a look at (perhaps just the first 10 frames or so?)

**Comment by vjlbym** [comment]
So when I try to load only a few frames, it loads fine. I can cut this file down to 4.2 gb and even that loads fine. I can make the original file public on S3 if you are interested to test it. Is there any size limit on the maximum tiff file loaded into sima with the tiff reading module used in it?

**Comment by nbdanielson** [comment]
Interesting -- there might be a frame limit in the multipage tiff module we use.  If your datasets are getting that big, it might be worth looking into saving them as HDF5 -- we use it for very large datasets (~40gb) with no issues

**Comment by vjlbym** [comment]
Oh, OK. Do you know of a way to convert from TIFF to HDF5? ImageJ is throwing an error saying "length is exceeded". Do you collect data as HDF5 or convert it after acquisition? If so, how do you convert? Thanks!

Also, if you think my issue is potentially going to be a general one, it might be worth catching an error if someone runs a single frame sequence for motion correction. Currently, the only error is "failed to estimate positive gains".

**Comment by vjlbym** [comment]
I tried reading up more on PIL, which seems to be tiff importer. I couldn't find any frame or size limit. It's somewhere between 4.2gb and 5gb, I think. Might be worth putting that info in the documentation if there is indeed a limit. Thanks a lot again!

**Comment by nbdanielson** [comment]
I agree, better error handling would be appropriate here.  We’ll add a note to the docs as well, thanks for looking into this.

In regards to .tif to HDF5 conversion, we iterate over a directory of .tif files and use PIL.Image to read the file and h5py.File to write the data to an open H5 file

**Comment by vjlbym** [comment]
Thanks! So if that's what you guys are doing, do you think just reading individual tiff files in a directory will work for loading in the data as tiff for motion correction? I don't really need to save the raw data as hdf5 as long as I can save the motion corrected data.

**Comment by vjlbym** [comment]
I checked that the full dataset can be loaded into SIMA by reading individual tiff files. So the issue really was just the PIL reader for a single TIFF stack. Thanks a lot!

**Comment by vjlbym** [comment]
Hey I just reopened to add one more thing if you guys are considering this issue. export_frames also fails when the TIFF file is larger than 4gb. I exported the motion corrected series as HDF5 to get around this but the file size was really large; it was in fact twice as large as the original tiff stack. Is there a way to specify compression for HDF5? Thanks again!

**Comment by jzaremba** [comment]
We'll better document the ~4GB limit of TIFF files both for importing and exporting, thanks for the info.

Looking at the HDF5 export code, we are writing the data as a 'float32' array, which probably explains the doubling in size if your data was originally 16-bit TIFFs. Compressing h5 file is fairly straightforward, I'll look in to adding that as option to export_frames. We use it with our raw data, so I don't foresee any issues implementing this.

I'm going to close this for now and open a new issue, but if  you are still having related issues feel free to re-open. Thanks!
