### ISSUE TITLE
HDF5 export_frames error

### ISSUE THREAD

**Issue by vjlbym** [losonczylab/sima#199]
Hi guys, 

I am still working on finishing up the analysis I mentioned in [Issue 195] (https://github.com/losonczylab/sima/issues/195). I have been running SIMA on Amazon EC2. I had a 12.2 gb set of 16-bit tiff files representing individual frames of the data. I ran motion correction on EC2 and it worked fine. This EC2 instance was a really beefy computer with 64gb RAM. I then exported a 23gb hdf5 file containing all the frames. But I had a ton of troubles uploading the data from EC2 onto S3. So as a workaround, I exported the .sima directory containing the dataset and sequences pickled files. On downloading those to a local machine, I realized that the paths were still for EC2. So I unpickled the files and changed all paths myself so as to be appropriate for the local machine, pickled them again and updated the files. Then, in trying to export an hdf5 file, the following code worked fine and wrote exactly up to 12gb into the file but then gave an error saying that h5py cannot convert a unicode character. This seems to be a [known h5py error] (https://github.com/h5py/h5py/issues/289) and is acknowledged in the SIMA code. But I tried tracking down where the unicode is coming from in SIMA and failed. Do you guys have any thoughts? 

The one thing giving me pause is that exactly 12gb was written into the h5 file. So I am wondering if this is again some memory related issue. My local machine has 16gb of RAM. 

As a related question, when you write into an hdf5 file, do you store all the data in RAM or do you write the file piece by piece such that there is no RAM overload but there is a significant time spent in writing to the disk?

Thanks!

```
import sima

% cd /home/stuberlab/simadata

dataset = sima.ImagingDataset.load('P7 Background D2 motioncorrected.sima')

#export your motion corrected data as a tiff stack to use in imageJ

dataset.export_frames(['P7 Background D2_mc.h5'], fmt='HDF5')
```
​

/home/stuberlab/simadata

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-5f32ef1df787> in <module>()
      3 dataset = sima.ImagingDataset.load('P7 Background D2 motioncorrected.sima')
      4 #export your motion corrected data as a tiff stack to use in imageJ
----> 5 dataset.export_frames(['P7 Background D2_mc.h5'], fmt='HDF5')

/home/stuberlab/anaconda/lib/python2.7/site-packages/sima/imaging.pyc in export_frames(self, filenames, fmt, fill_gaps, scale_values)
    627             raise TypeError('Improperly formatted filenames')
    628         for sequence, fns in zip(self, filenames):
--> 629             sequence.export(fns, fmt, fill_gaps, self.channel_names)
    630 
    631     def export_signals(self, path, fmt='csv', channel=0, signals_label=None):

/home/stuberlab/anaconda/lib/python2.7/site-packages/sima/sequence.pyc in export(self, filenames, fmt, fill_gaps, channel_names)
    435                 f['imaging'].dims[idx].label = label
    436             if channel_names is not None:
--> 437                 f['imaging'].attrs['channel_names'] = np.array(channel_names)
    438             f.close()
    439 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2405)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py-2.4.0/h5py/_objects.c:2362)()

/home/stuberlab/anaconda/lib/python2.7/site-packages/h5py/_hl/attrs.pyc in __setitem__(self, name, value)
     72         use the methods create() and modify().
     73         """
---> 74         self.create(name, data=value, dtype=base.guess_dtype(value))
     75 
     76     @with_phil

/home/stuberlab/anaconda/lib/python2.7/site-packages/h5py/_hl/attrs.pyc in create(self, name, data, shape, dtype)
    111                 if dtype is None:
    112                     dtype = numpy.dtype('f')
--> 113                 htype = h5t.py_create(dtype, logical=True)
    114 
    115             if shape is None:

h5py/h5t.pyx in h5py.h5t.py_create (-------src-dir-------/h5py-2.4.0/h5py/h5t.c:15500)()

h5py/h5t.pyx in h5py.h5t.py_create (-------src-dir-------/h5py-2.4.0/h5py/h5t.c:15331)()

h5py/h5t.pyx in h5py.h5t.py_create (-------src-dir-------/h5py-2.4.0/h5py/h5t.c:15291)()

TypeError: No conversion path for dtype: dtype('<U1')

**Comment by jzaremba** [comment]
I think there are 2 issues here, the unicode strings and the memory-inefficient exporting of the h5 file.

It looks like the channel_names issue might have been addressed already:
https://github.com/losonczylab/sima/blob/master/sima/sequence.py#L463

What version of SIMA are you running?

For the memory issue, it looks we are initializing the entire output array in memory, which there's no need to do. Instead we should be able to initialize the h5 dataset first on disk and write directly to it, so there's no need to have more than 1 frame in memory at a time.

**Comment by vjlbym** [comment]
I am running SIMA 1.2.0 and that's the issue for the unicode error. I'll update mine. Thanks!

Yeah, the memory issue would be good to fix since as things stand, there's no way to write more than 80% or so of the RAM. I am wondering how you guys were exporting files up to 40 gb as [mentioned by] (https://github.com/losonczylab/sima/issues/195#issuecomment-139051850) @nbdanielson Do you just have a computer with a ridiculous RAM or do you use some other function to work with those h5 files?

**Comment by jzaremba** [comment]
For our lab workflow we actually don't ever export motion corrected data back to HDF5, which is probably why we haven't come across these issues before. We have a viewer web app that directly reads SIMA directories (or h5 files) that we use for checking the motion correction and looking at the movies. We are working on stabilizing/cleaning this up so we can hopefully get it up on github soon.

We do convert individual TIFF files to a single HDF5 file to make things easier to work with and these files can be ~40GB like Nathan said. This is the format of our raw data at the start of our SIMA pipeline and by the end we are basically just worked with the extracted dF/F traces. Everything within SIMA should be relatively memory efficient, only holding on to frames that are needed at the time, so you shouldn't need a ton of memory to run anything.

**Comment by vjlbym** [comment]
That makes sense. My only current limitation is due to an export of the motion corrected file back to an hdf5 file. Do you use the SIMA function to convert the tiff files to HDF5 initially? Or do you use a separate script to do that? Also, one last question before I close this issue: do you hand-draw ROIs for 2P data or use automatic signal extraction through stICA? Thanks a ton, again!

**Comment by vjlbym** [comment]
Also, how long does it take to motion correct the 40GB files? For even 4 gb files, our computers take many hours, which is why we started doing stuff on Amazon EC2.

**Comment by jzaremba** [comment]
We have a separate script for converting from TIFF to HDF5. It's specific to our Prairie/Bruker scope (it reads/parses their auto-generated xml/cfg file), but you should be grab the core writing part if you are coming from some other system. If it's helpful the script is up [here](https://gist.github.com/jzaremba/f7adde4dced95cbdbf9b), feel free to take anything from it.

Personally, I use the CA1PC segmentation method in SIMA combined with hand-drawing and manual cleanup. Most of my data is from the same field of view over weeks, so I usually draw one set carefully and then transform/copy those ROIs to subsequent days with [ROIBuddy](https://github.com/losonczylab/roibuddy). I know other people in the lab who are imaging other cellular compartments (boutons/axons/dendrites) have had success using the stICA method for segmentation.

Motion correction can take a long time to run with large datasets. You can speed up the initial coarse whole-frame alignment step of the HMM motion correction algorithm by setting the n_processes argument >1, but otherwise there's not much to do. Speeding up motion correction is always on the TODO list, but we don't have a faster method right now.

**Comment by vjlbym** [comment]
Thanks a ton. I really appreciate your help!
