### ISSUE TITLE
TIFF file saving bug

### ISSUE THREAD

**Issue by pkaifosh** [losonczylab/sima#2]
### Problem
TIFF files saved with SIMA's ImagingDataset.export_frames() cannot be opened with MATLAB.

### Details
Since this problem can be corrected by changing the RowsPerStrip tag of the TIFF file to equal the number of rows in the image, this problem may be due to improper setting of these tags in tifffile.py. 

### Work-arounds
A) Open and then re-save the TIFF files using ImageJ. They can then be opened with MATLAB.
B) Edit the RowsPerStrip tag of the image files.

**Comment by darkmajere** [comment]
Issue has been removed. Updated version of ImagingDataset.export_frames() can extract the tiff files from the dataset for ready to be opened in MATLAB.

**Comment by pkaifosh** [comment]
Fixed by #82 and #81.
