### ISSUE TITLE
export_frames doesn't actually implement 'scale_values'

### ISSUE THREAD

**Issue by jzaremba** [losonczylab/sima#200]
It's listed as an optional argument (as in 'export_averages'), but it's not actually implemented.

We need to be a bit more careful with how we implement it since we don't want to load all the data in to memory like we do with export_averages.

This should be in Sequence.export. First iterate through the sequence to determine the max and then rescale during a second iteration that writes the data.

**Comment by nbdanielson** [comment]
Just took a look at this -- my impression is that this is actually being implemented correctly in ```ImagingDataset.export_averages```.  It looks like ```ImagingDataset.export_frames``` is where we need to make a change (i.e. we need to pass the ```scale_values``` variable into ```Sequence.export``` and implement the functionality there.  @jzaremba if this is correct I'll make this change

**Comment by jzaremba** [comment]
Yeah, that's correct. We could also just 'fix' the docs, since no one seems to be needing this feature right now.

**Comment by nbdanielson** [comment]
Should be fixed in https://github.com/losonczylab/sima/pull/217
