### ISSUE TITLE
warnings.warn('Could not align all frames.') and warnings.warn('No finite observation probabilities.')

### ISSUE THREAD

**Issue by rzemla** [losonczylab/sima#214]
Dear Developers,

I am running SIMA on a 1024x1024x8000 frame stack at 15Hz resonance acquisition mode. I acquired the tiff stack (~15 GB) and then converted it to hdf5 file format (~32 GB).  It took about 42 hours to run on a cluster. SIMA generated the following errors:

/local/apps/python/2.7.3/lib/python2.7/site-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/motion/frame_align.py:505: UserWarning: Could not align all frames.
  warnings.warn('Could not align all frames.')
/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/motion/hmm.py:811: UserWarning: No finite observation probabilities.
  warnings.warn('No finite observation probabilities.')

At the end of the script when converting from the motion corrected dataset to TIFF16 it generated the following:

 Traceback (most recent call last):
  File "./simaHPC_hdfin_tiffout_ver1.3.py", line 42, in <module>
    dataset.export_frames([[[export_name]]],fmt = 'TIFF16')
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/imaging.py", line 613, in export_frames
    sequence.export(fns, fmt, fill_gaps, self.channel_names)
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/sequence.py", line 439, in export
    f.write_page(channel.astype('uint16'))
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/misc/tifffile.py", line 372, in write_page
    self._write(self._offset_format, pos)
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/misc/tifffile.py", line 363, in _write
    self.fh.write(pack(arg, *args) if args else arg)
  File "/local/apps/python/2.7.3/lib/python2.7/site-packages/sima/misc/tifffile.py", line 362, in pack
    return struct.pack(self._byteorder+fmt, *val)
struct.error: 'I' format requires 0 <= number <= 4294967295

I assume that this is due to the conversion from the 32-bit HDF5 format to the 16 bit TIFF format. The same code and conversion sequence works for a 1000 frame slice of the whole stack. I would greatly appreciate any suggestions to get this up and running as well as any possible speed enhancement. 

Sincerely,

**Comment by jzaremba** [comment]
The issue actually is that your data is too large to export as a TIFF stack, there is a limit inherent in the file format itself. You should be able to export it without problem as an HDF5 file.

On the issue of time, we regularly process data of that size and motion correction shouldn't take close to that long to run. Is that time for the entire conversion/processing/export pipeline? What version of SIMA are you running?

Also, you should be able to either match the bit depth of the TIFF files or use lossless compression when converting to HDF5 in order to avoid the doubling of the file size during the conversion.

Hopefully this helps!

**Comment by rzemla** [comment]
Great I will try that out! The only problem I have with large HDF5 files (in this case 32 GB) is that I cannot view them in ImageJ without generating file too large errors or dealing with out-of-memory issues. Do you know of any efficient way to deal with that i.e. loading slices of the HDF5 stack and offloading the rest to storage?

Regarding the warnings, do you happen to know how that affects the end processing of the file?

Best,
Roland

**Comment by jzaremba** [comment]
We use a viewer that @jbowler06 developed that can efficiently view both HDF5 files and also SIMA directories (without needing to export the final movie).

**Comment by nbdanielson** [comment]
@rzemla I'm not sure about the ```could not align all frames``` warning.  Regarding the ```no finite observation probabilities```, I believe this warning is given when the algorithm calculates a y-displacement that's outside the window of max displacements (@pkaifosh, please correct me if I'm wrong here).

Often times we've had good motion-correction even with this warning (you should view the corrected movie afterwards to see how it looks), so it's not necessarily disastrous.  If you play with the maximum allowable y-displacements (which should be determined after watching the raw movie) you may be able to prevent this warning

**Comment by rzemla** [comment]
Thanks I will try to get the viewer up and running! I think that will help us verify whether the warnings related to alignment are significant.

**Comment by nbdanielson** [comment]
I'm going to close this issue, as it seems the central problem has been resolved.  We can re-open if necessary.
