### ISSUE TITLE
Single plane ROIs don't always show in ROIBuddy

### ISSUE THREAD

**Issue by jzaremba** [losonczylab/sima#77]
If you load a multi-plane dataset, switch to plane 1, and then load a single-plane dataset, none of the ROIs will show. It looks like the active plane for the new dataset is being set correctly, so I'm not sure where this is getting confused. The set loads fine on its own, or if you are on plane 0 of a multi-plane dataset when you load the new one. If anyone has a chance to look into this I have example datasets.

**Comment by nbdanielson** [comment]
This behavior occurs if you load multiple datasets that have unequal numbers of planes.  This is not supported by ROI Buddy at the present moment.
