### ISSUE TITLE
stica cannot be called through ImagingDataset object

### ISSUE THREAD

**Issue by nk53** [losonczylab/sima#94]
Line 660 in imaging.py, `elif method is 'ca1pc':`
Should be changed to, `elif method is 'stica':`

**Comment by nk53** [comment]
Issue present in version 0.3.1

**Comment by pkaifosh** [comment]
@nk53 Thanks for the bug report nevertheless. We encourage you to join our user group (https://groups.google.com/forum/#!forum/sima-users) to receive timely updates about newly released versions.
