### ISSUE TITLE
automated testing on Windows

### ISSUE THREAD

**Issue by pkaifosh** [losonczylab/sima#95]
http://www.appveyor.com/
Referenced here: https://packaging.python.org/en/latest/multiple_python_versions.html

**Comment by pkaifosh** [comment]
Also important: https://packaging.python.org/en/latest/appveyor.html

**Comment by nbdanielson** [comment]
I created an appveyor branch on my fork and an account on appveryor as well:
https://ci.appveyor.com/project/nbdanielson/sima-374

I added a skeleton appveyor.yml script (comparable to the .travis.yml) that so far just initializes the box and downloads the repo.  When I'm back in front of a windows terminal i can add in the dependency installs
