### ISSUE TITLE
workflow.py example throws an exception when calculating ROIs (PART 3)

### ISSUE THREAD

**Issue by ranr01** [losonczylab/sima#97]
When running workflow.py when get's the following exception:

ValueError: operands could not be broadcast together with shapes (31124,) (31500,) 

Here is the Traceback:

Traceback (most recent call last):
  File "workflow.py", line 107, in <module>
    dataset.segment(segmentation_approach, 'auto_ROIs')
  File "/home/ranr/projects/sima/sima/imaging.py", line 664, in segment
    rois = method.segment(self)
  File "/home/ranr/projects/sima/sima/segment.py", line 65, in segment
    rois = self._segment(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 92, in _segment
    return self._segment_plane(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 603, in _segment_plane
    return self._normcut_method.segment(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 65, in segment
    rois = self._segment(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 92, in _segment
    return self._segment_plane(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 525, in _segment_plane
    affinity = params.affinity_method.calculate(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 397, in calculate
    self._setup(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 431, in _setup
    super(AffinityMatrixCA1PC, self)._setup(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 394, in _setup
    self._correlations = self._calculate_correlations(dataset)
  File "/home/ranr/projects/sima/sima/segment.py", line 384, in _calculate_correlations
    num_pcs=self._params.num_pcs, verbose=self._params.verbose)
  File "/home/ranr/projects/sima/sima/segment.py", line 167, in _offset_corrs
    verbose=verbose)
  File "/home/ranr/projects/sima/sima/segment.py", line 288, in _OPCA
    DatasetIterable(dataset, ch), num_pcs=num_pcs, verbose=verbose)
  File "/home/ranr/projects/sima/sima/oPCA.py", line 90, in EM_oPCA
    for X in (data):
  File "/home/ranr/projects/sima/sima/segment.py", line 204, in __iter__
    frame[..., self.channel].reshape(-1) - self.means)
ValueError: operands could not be broadcast together with shapes (31124,) (31500,)

**Comment by pkaifosh** [comment]
It just ran fine for me. See below. Can you make sure that you are running the most recent version and that you have cleaned out anything from the workflow_data directory that wasn't there in the original download. If there is still a problem, try running in the debugger (i.e. python -m pdb workflow.py) and see if you can find out additional information about what is going on.

```
In [1]: %run workflow.py
TIFF filenames:
[['workflow_data/Cycle01_Ch1.tif', 'workflow_data/Cycle01_Ch2.tif'], ['workflow_data/Cycle02_Ch1.tif', 'workflow_data/Cycle02_Ch2.tif'], ['workflow_data/Cycle03_Ch1.tif', 'workflow_data/Cycle03_Ch2.tif'], ['workflow_data/Cycle04_Ch1.tif', 'workflow_data/Cycle04_Ch2.tif'], ['workflow_data/Cycle05_Ch1.tif', 'workflow_data/Cycle05_Ch2.tif'], ['workflow_data/Cycle06_Ch1.tif', 'workflow_data/Cycle06_Ch2.tif'], ['workflow_data/Cycle07_Ch1.tif', 'workflow_data/Cycle07_Ch2.tif'], ['workflow_data/Cycle08_Ch1.tif', 'workflow_data/Cycle08_Ch2.tif'], ['workflow_data/Cycle09_Ch1.tif', 'workflow_data/Cycle09_Ch2.tif'], ['workflow_data/Cycle10_Ch1.tif', 'workflow_data/Cycle10_Ch2.tif'], ['workflow_data/Cycle11_Ch1.tif', 'workflow_data/Cycle11_Ch2.tif'], ['workflow_data/Cycle12_Ch1.tif', 'workflow_data/Cycle12_Ch2.tif'], ['workflow_data/Cycle13_Ch1.tif', 'workflow_data/Cycle13_Ch2.tif'], ['workflow_data/Cycle14_Ch1.tif', 'workflow_data/Cycle14_Ch2.tif'], ['workflow_data/Cycle15_Ch1.tif', 'workflow_data/Cycle15_Ch2.tif']]
Estimating model parameters.
Estimating displacements for cycle  0
Estimating displacements for cycle  1
Estimating displacements for cycle  2
Estimating displacements for cycle  3
Estimating displacements for cycle  4
Estimating displacements for cycle  5
Estimating displacements for cycle  6
Estimating displacements for cycle  7
Estimating displacements for cycle  8
Estimating displacements for cycle  9
Estimating displacements for cycle  10
Estimating displacements for cycle  11
Estimating displacements for cycle  12
Estimating displacements for cycle  13
Estimating displacements for cycle  14
Overwrite existing directory? y
Output filenames:
[[['workflow_data/Cycle01_Ch1_corrected.tif', 'workflow_data/Cycle01_Ch2_corrected.tif']], [['workflow_data/Cycle02_Ch1_corrected.tif', 'workflow_data/Cycle02_Ch2_corrected.tif']], [['workflow_data/Cycle03_Ch1_corrected.tif', 'workflow_data/Cycle03_Ch2_corrected.tif']], [['workflow_data/Cycle04_Ch1_corrected.tif', 'workflow_data/Cycle04_Ch2_corrected.tif']], [['workflow_data/Cycle05_Ch1_corrected.tif', 'workflow_data/Cycle05_Ch2_corrected.tif']], [['workflow_data/Cycle06_Ch1_corrected.tif', 'workflow_data/Cycle06_Ch2_corrected.tif']], [['workflow_data/Cycle07_Ch1_corrected.tif', 'workflow_data/Cycle07_Ch2_corrected.tif']], [['workflow_data/Cycle08_Ch1_corrected.tif', 'workflow_data/Cycle08_Ch2_corrected.tif']], [['workflow_data/Cycle09_Ch1_corrected.tif', 'workflow_data/Cycle09_Ch2_corrected.tif']], [['workflow_data/Cycle10_Ch1_corrected.tif', 'workflow_data/Cycle10_Ch2_corrected.tif']], [['workflow_data/Cycle11_Ch1_corrected.tif', 'workflow_data/Cycle11_Ch2_corrected.tif']], [['workflow_data/Cycle12_Ch1_corrected.tif', 'workflow_data/Cycle12_Ch2_corrected.tif']], [['workflow_data/Cycle13_Ch1_corrected.tif', 'workflow_data/Cycle13_Ch2_corrected.tif']], [['workflow_data/Cycle14_Ch1_corrected.tif', 'workflow_data/Cycle14_Ch2_corrected.tif']], [['workflow_data/Cycle15_Ch1_corrected.tif', 'workflow_data/Cycle15_Ch2_corrected.tif']]]
Continue? (y/n): y
Continue? (y/n): y
```

**Comment by ranr01** [comment]
You are right. In a clean directory I get no exception as well.
It's probably because the .sima library was rewritten several times. Perhaps a clean operation needs to be performed when a library is overwritten (should it be optional?) ?

**Comment by pkaifosh** [comment]
OK. I'll close this now. If you think of anything that could be added to the setup script to help with this, then that would be great.
