### ISSUE TITLE
Conversion of a sliced sequence to a numpy.ndarray 

### ISSUE THREAD

**Issue by ranr01** [losonczylab/sima#99]
Right now one can convert a sequnce to a numpy array like this:

```python
>>import numpy as np
>>array_seq=np.array(seq)
```
however if one want to convert just a slice of the sequence, an exception is thrown:

```python
>> array_slice = np.array(seq[0,0,:,:,1])
-------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-eb9949ee96b7> in <module>()
----> 1 array(dataset.sequences[0][0,0,:,:,0])

ValueError: setting an array element with a sequence.
```

**Comment by pkaifosh** [comment]
The problem seems to be that numpy.array() function fails when the sequence has just a single frame. I'm not sure what we would have to change to fix this. The Sequence.asarray() method that I just added works in this case.

**Comment by ranr01** [comment]
We can add an __array__ function to the Sequnce class that calls the asarray function.
This should work according to the numpy docs. 

see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

will do it later...

**Comment by pkaifosh** [comment]
Sure. We can just rename the ```aarray()``` to be ```__array__()```

**Comment by ranr01** [comment]
That will be even better. We should alos update the docs to reflect that this is the "official" way to get an numpy.ndarray from a Sequence (if this is not already the case).
